### ISSUE TITLE
cap_setgroups() asserts

### ISSUE THREAD

**Issue by stsp** [AndrewGMorgan/libcap_mirror#1]
Hi.

cap_setgroups() uses setgroups() glibc
call if _libcap_overrode_syscalls==0.
This is a non-working combination, as
glibc is trying to invoke the syscall on
all threads. But libcap adjusts the cap
only for the calling thread. When glibc
sees that some treads succeeded and
some failed, it aborts.

Things work properly with
_libcap_overrode_syscalls==1, but I
haven't found a simple way of setting
it to 1 in ubuntu jammy. If I build libcap
by hands, I can override psx_load_syscalls(),
hence preserving _libcap_overrode_syscalls.
But in ubuntu jammy this function is not
weak, and I can't override it.

It would be great if libcap provides the
per-process variants of its functions, but
I don't think its possible. glibc is doing
that using internal nptl impl, which libcap
can't use.
So I think libcap should just always avoid
using glibc wrappes, as all of them act
per-process, not per-thread. I mean, all:
not only setgroups, but also setuid/setgid/whatever
else.

**Comment by AndrewGMorgan** [comment]
This bug tracker is not used. The GitHub copy of `libcap` is a mirror only. The correct place to file a bug against `libcap` is documented on https://sites.google.com/site/fullycapable/ and also mentioned in the man pages.

Please read https://sites.google.com/site/fullycapable/who-ordered-libpsx for our position on threading and `libcap`. In general per-thread security context is not meaningful security at all because of shared memory and shared interrupt handling.

**Comment by stsp** [comment]
Thank you, I've got it to work with
libpsx from git. But in ubuntu 22.04
psx_load_syscalls in libcap.so.2.44
is not a weak symbol, so override
doesn't seem to work.
Can you check what's wrong with
ubuntu's libcap? Or is this the wrong
place to ask?

**Comment by stsp** [comment]
Also, even with git I've got it to work
only with static libpsx. With shared libpsx
the override doesn't work, so why to
build shared libpsx?

**Comment by stsp** [comment]
I also checked other ubuntu versions
and fedora rpm, and psx_load_syscalls
is not weak there. Which is more than
strange, when its defined as weak in a
sources...

**Comment by stsp** [comment]
Hmm, -flto=auto is what makes the
symbol non-weak (on gcc, fine with clang).
But this appears to be not the source of
my problem.
Looking further,,,

**Comment by stsp** [comment]
Found the problem and filled this ticket:
https://bugzilla.kernel.org/show_bug.cgi?id=219168

**Comment by AndrewGMorgan** [comment]
FWIW I'm reverting the policy noted in https://github.com/AndrewGMorgan/libcap_mirror/issues/1#issuecomment-2292546983 and promoting this GitHub bug tracker to being the official one.

The future of bugzilla.kernel.org is being actively debated with the chief sentiment that it be disbanded. I don't want to have to deal with the ambiguity of a migration on a timeline I don't control. So, moving forward, this will be the bug tracker of record.
